export const Data =[

    {
        Id:1,
        ImgUrl:'https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcQhNehHpq2Lq0C5iRKjk0RbCIS5wo5I2RNaEQ&s',
        Model:'z1',
        Company:'Samsung',
        Cost:20000
     },
     {
        Id:2,
        ImgUrl:'https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcQhNehHpq2Lq0C5iRKjk0RbCIS5wo5I2RNaEQ&s',
        Model:'V5',
        Company:'Samsung',
        Cost:50000
     },
     {
        Id:3,
        ImgUrl:'https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcQhNehHpq2Lq0C5iRKjk0RbCIS5wo5I2RNaEQ&s',
        Model:'V8',
        Company:'Sony',
        Cost:10000
     },
     {
        Id:4,
        ImgUrl:'https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcR0hRKfHXL0jldf40lCqFPVv3bdceD0_qQiDg&s',
        Model:'z10',
        Company:'Samsung',
        Cost:20000
     },
     {
        Id:5,
        ImgUrl:'https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcSUusmMIKXUJemtKUreospeVfp7MjG9bmbjnA&s',
        Model:'T34',
        Company:'RealMe',
        Cost:70000
     },
     {
        Id:6,
        ImgUrl:'https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcSUusmMIKXUJemtKUreospeVfp7MjG9bmbjnA&s',
        Model:'M40',
        Company:'Sony',
        Cost:35000
     },
     {
        Id:7,
        ImgUrl:'https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcR0hRKfHXL0jldf40lCqFPVv3bdceD0_qQiDg&s',
        Model:'K11',
        Company:'Samsung',
        Cost:87976
     },
     {
        Id:8,
        ImgUrl:'https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcSUusmMIKXUJemtKUreospeVfp7MjG9bmbjnA&s',
        Model:'Z25',
        Company:'RealMe',
        Cost:10000
     },
     {
        Id:9,
        ImgUrl:'https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcSUusmMIKXUJemtKUreospeVfp7MjG9bmbjnA&s',
        Model:'X10',
        Company:'RealMe',
        Cost:20000
     },
     {
        Id:10,
        ImgUrl:'https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcR0hRKfHXL0jldf40lCqFPVv3bdceD0_qQiDg&s',
        Model:'P1i',
        Company:'Samsung',
        Cost:20000
     },
     {
        Id:8,
        ImgUrl:'https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcSUusmMIKXUJemtKUreospeVfp7MjG9bmbjnA&s',
        Model:'Z25',
        Company:'RealMe',
        Cost:10000
     },
     {
        Id:9,
        ImgUrl:'https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcSUusmMIKXUJemtKUreospeVfp7MjG9bmbjnA&s',
        Model:'X10',
        Company:'RealMe',
        Cost:20000
     }



]